[package]
name = "ccaarch64"
version = "0.1.0"
edition = "2024"


[[bin]]
name="evelyn"
path="kernel/init.rs"


[dependencies]



[profile.release]
lto = true

[profile.dev]
lto = false
opt-level = 0
codegen-units = 1
debug = true
