[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
rustflags = ["-C", "link-arg=-Tkernel.ld", "-C", "force-frame-pointers=no"]
runner="./script/run-qemu.sh"


[unstable]
unstable-options=true
build-std=["core","compiler_builtins"]
build-std-features=["core/optimize_for_size","compiler-builtins-mem"]
trim-paths=true